apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: homework
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: hw
    tier: gold
  name: homework-1
  namespace: homework
spec:
  containers:
  - image: shekeriev/k8s-oracle
    name: homework-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: hw
  name: homework-2
  namespace: homework
spec:
  containers:
  - image: shekeriev/k8s-oracle
    name: homework-2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: homework-svc
  name: homework-svc
  namespace: homework
spec:
  ports:
  - name: 5000-5000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: homework-svc
  type: NodePort
status:
  loadBalancer: {}
